name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive

# Cache compiled kernel
          - name: Cache kernel
            uses: actions/cache@v3
            with:
              path: /tmp/aesd-autograder/linux-stable
              key: ${{ runner.os }}-kernel-cache-${{ hashFiles('path/to/kernel/config/file') }}
              restore-keys: |
                ${{ runner.os }}-kernel-cache-
          
          # Skip kernel build if cached version exists
          - name: Build or reuse kernel
            run: |
              if [ ! -f /tmp/aesd-autograder/linux-stable/Image ]; then
                echo "Kernel image not found, recompiling..."
                ./build-kernel.sh  # Replace with actual kernel build script
              else
                echo "Kernel image found, skipping recompilation."
              fi

          - name: Run full test
            run: ./full-test.sh
